sonisori/Server

- .editorconfig
- build.gradle
- config/configuration_1_3.dtd
- config/naver-checkstyle-rules.xml
- config/naver-checkstyle-suppressions.xml
- config/naver-intellij-formatter.xml
- config/suppressions_1_1.dtd
- Naver Checkstyle 규칙 적용을 위해 해당 xml 파일을 추가했습니다.
- 코드 스타일 일관성을 위해 `.editorconfig` 파일을 추가하였습니다.
- 들여쓰기 스타일, 줄 끝, 최대 줄 길이 등 
- `build.gradle` 파일에 Checkstyle 플러그인 및 설정을 추가하였습니다.  
- 더 세밀한 코드 스타일 규칙 정의를 위해 formatter 파일을 추가하였습니다
- `.editorconfig` 파일: 코드 스타일 설정이 올바르게 적용되었는지 확인해주세요. 
- 특히, 각 항목의 설정이 프로젝트에 적절한지 검토가 필요합니다.
- `build.gradle` 수정 사항: Checkstyle 설정이 올바르게 적용되었는지, 확인해주세요
- `./gradlew.bat checkstyleMain checkstyleTest` 명령어를 입력하였을때 성공해야 됩니다
| 사진 | 설명 |
| --- | --- |
|![image](https://github.com/user-attachments/assets/b47e5cea-9176-49a0-b84d-021c3339a4f3)|성공 시 사진과 같습니다|
- naver-intelliJ-formatter.xml 파일 적용 방법
- `File > Settings > Editor > Code Style > Java > 톱니바퀴 아이콘 클릭 > Import Scheme > IntelliJ IDEA code style XML 선택 > naver-intelliJ-formatter.xml` 파일 선택
- `File > Settings > Tools > …
> chore: Naver Checkstyle 설정 추가 및 적용 

- .github/workflows/ci.yml
- build.gradle
- GitHub Actions를 사용하여 Java CI 파이프라인을 구축했습니다.
- 다음 단계들을 포함했습니다:
- 코드 체크아웃
- application.properties 파일 설정
- Gradle Wrapper에 실행 권한 부여
- JDK 21 및 Gradle 환경 설정
- 단위 테스트 및 빌드 실행
- Checkstyle 검사를 통한 코드 품질 유지
| 사진 | 설명 |
| --- | --- |
|![image](https://github.com/user-attachments/assets/9a3eaf2b-ef43-4270-9ee7-7fe789aa923b) | 앞으로 PR이나 머지할 때마다 github action을 통해 테스트를 하고 결과가 나옵니다 |
- PR에서 CI 실패 시 해당 오류를 수정해주세요! 
closed #6
> chore: github action을 이용한 CI 파이프라인 구축

- src/main/java/site/sonisori/sonisori/auth/jwt/entity/RefreshToken.java
- src/main/java/site/sonisori/sonisori/auth/jwt/repository/RefreshTokenRepository.java
- refresh token을 저장하기 위한 초기 설정을 추가하였습니다
- 14일간 저장합니다.
- refresh token은 jwt가 아니라 UUID로 저장하면 좋을 것 같습니다 
closed #11
> chore: Redis 기반 RefreshToken 엔티티 및 Repository 추가

- src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
- src/main/java/site/sonisori/sonisori/common/response/ErrorResponse.java
- src/main/java/site/sonisori/sonisori/exception/GlobalExceptionHandler.java
- `GlobalExceptionHandler`를 추가하여 `NullPointerException`, `MethodArgumentNotValidException`, `HandlerMethodValidationException` 등을 처리하는 글로벌 예외 처리 로직 구현.
- `ErrorMessage` enum에 예외에 대한 상세한 메시지 제공.
- `ErrorResponse` 클래스를 활용하여 일관된 에러 응답 포맷 제공.
- 에러 메시지의 일관성과 사용자 친화성을 확인해 주세요.
closed #14
> feat: global error 처리 및 사용자 정의 error response 추가

- src/main/java/site/sonisori/sonisori/exception/GlobalExceptionHandler.java
- src/main/resources/logback-spring.xml
**application properties에 다음 내용을 추가해주세요!!!!**
```properties
spring.profiles.active=local
logging.config=classpath:logback-spring.xml
logging.file.path=./logs
```
- 로그 설정을 위해 `logback-spring.xml` 설정 파일을 작성하였습니다.
- 콘솔 및 파일 로그 출력 형식을 일관성 있게 적용하였습니다.
- 로컬 환경에서는 console만 나오고, 개발 환경과 운영 환경에서는 콘솔과 더불어 파일까지 저장됩니다.
- 개발환경의 설정에서 작업하고 로그 파일로 저장하고 싶다면 `application.properties`의 `spring.profiles.active` 부분을 `dev`로 수정하면 됩니다!
- `GlobalExceptionHandler` 클래스 예외 처리가 필요한 파일에서 예외 처리 시 로깅을 적용하였습니다
- console 찍을 일이 있다면 console 대신 `log.info()`로 찍어서 확인하시면 됩니다! 그 후 필요없는 로그는 지워주세요! 
- 로깅 레벨(INFO, WARN, ERROR)이 적절히 설정되어 있는지 확인해 주세요.
- 로그 메시지가 적절한 레벨로 기록되고 있는지, 그리고 필요한 정보가 포함되어 있는지 중점적으로 봐 주세요.
- 추가적인 로깅 정보나 형식 개선에 대한 의견이 있으시면 말씀해주세요!!
- 파일의 경우 전체적인 로그를 저장하는 파일과 에러 메시지만 저장하는 파일 두 가지를 생성합니다.
- 파일의 최대 사이즈는 100MB이며, 최대 …
> feat: slf4j 로그 설정 추가 및 적용

- build.gradle
- src/main/java/site/sonisori/sonisori/auth/cookie/CookieUtil.java
- src/main/java/site/sonisori/sonisori/auth/jwt/JwtUtil.java
- src/main/java/site/sonisori/sonisori/auth/jwt/dto/TokenDto.java
- src/main/java/site/sonisori/sonisori/auth/jwt/exception/JwtExceptionFilter.java
- src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2User.java
- src/main/java/site/sonisori/sonisori/auth/oauth2/dto/OAuth2UserDto.java
- src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
- src/main/java/site/sonisori/sonisori/config/ExceptionHandlerConfig.java
- src/main/java/site/sonisori/sonisori/config/SecurityConfig.java
- src/main/java/site/sonisori/sonisori/repository/UserRepository.java
```properties
#jwt
spring.jwt.secret-key=
spring.jwt.access-expiration=1800
spring.jwt.refresh-expiration = 1209600
```
위 내용을 추가해주세요 
- jwtUtil 클래스를 JWT 생성 및 유효성 검사 기능 구현
- CookieUtil을 통한 쿠키 생성 및 삭제 메서드 구현
- JWT 관련 예외 필터(JwtExceptionFilter) 추가로 인증 오류 처리
- OAuth 사용자 정보와 UserDetails 인터페이스 통합
- SecurityConfig 클래스에서 시큐리티 및 CORS 설정 추가
- ExceptionHandlerConfig를 통한 인증 및 접근 권한 예외 처리 설정
- oauth2와 겹치는 내용이 있어서 그와 관련된 코드들은 되도록 빼고 작성하였습니다 
- oauth2 코드 추가 이후 추가할 내용이 있으니 이 점 염두해주세요!
- 현재 `getAuthentication` 메서드는 작성되지 않은 상태입니다. 추후 `CustomOAuth2Service` 등 사용자 정보를 로드하는 메서드를 작성하실 때 추가해주세요!
- 스프링 security context에 저장되어 사용자 인증 상태를 유지하는데 사용됩니다
- 또한  JWT 토큰을 검증하여 유효한 인증 객체를 SecurityContextHolder에 설정하는 `TokenFilter`가 아직 작성되지 않았습니다 (`getAuthentication` 메서드가 없어서..) 
- 그로 인해 security 설정도 아직 완벽하게 되어있지 않습니다! 필요한 파일들 …
> feat: JWT 인증 및 시큐리티 설정 추가

- src/main/java/site/sonisori/sonisori/common/SocialType.java
- src/main/resources/db/migration/V1__init.sql
- DB의 social type enum이 잘못 설정되어 있어 문제가 발생하므로 이를 수정하였습니다. 
- **_반드시 코드 실행 전에 mysql을 비워주세요_**
여기서 Drop Schema를 눌러 Schema를 삭제해주세요
그 후 해당 왼쪽 빈 화면에서 우클릭 후 Create Schema를 눌러 sonisori라는 schema를 생성해주세요
그리고 코드를 실행해주시기 바랍니다
- 원래 sql 파일을 한 번 만든 후 고치면 안 되지만 db안의 내용이 없어 임의로 수정하였습니다. 이점 유의해주시기 바랍니다
- 자체 회원가입과 로그인을 위한 `password` 필드도 추가하려고 했으나 entity와 함께 바꿔야해서 복잡해질까봐 처리하지 않았습니다.
closed #24
> fix: V1 sql의 social type enum 수정

- src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2SuccessHandler.java
- src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
- src/main/java/site/sonisori/sonisori/config/SecurityConfig.java
- src/main/java/site/sonisori/sonisori/controller/UserController.java
- src/main/java/site/sonisori/sonisori/dto/user/LoginRequest.java
- src/main/java/site/sonisori/sonisori/exception/GlobalExceptionHandler.java
- src/main/java/site/sonisori/sonisori/exception/InvalidUserException.java
- src/main/java/site/sonisori/sonisori/repository/UserRepository.java
- src/main/java/site/sonisori/sonisori/service/UserService.java
- 자체 로그인 api를 구현하였습니다. 
- 로그인 성공시 쿠키가 생성되고 redis에 refresh token이 저장되는 것을 확인했습니다.
- 회원 정보가 올바르지 않을 경우에 대한 에러 처리를 진행하였습니다. 
| 사진 | 설명 |
| --- | --- |
|![image](https://github.com/user-attachments/assets/cc1c3cb0-c09d-47b7-905b-f0ed320fb960) | 회원 정보 틀릴 경우|
|![image](https://github.com/user-attachments/assets/1f459eab-d176-4671-8d4c-100997c9fe71)| 로그인 성공 |
|![image](https://github.com/user-attachments/assets/a922b029-35ae-4ed3-aea5-489c459df96c)| 로그인 성공 시 쿠키 생성 |
|![image](https://github.com/user-attachments/assets/e75ae806-6391-46ab-81e9-3092d0125503)| redis에 refresh token 저장됨|
closed #28
> feat: 자체 로그인 api 구현

- src/main/java/site/sonisori/sonisori/auth/CustomUserDetails.java
- src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
- src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2SuccessHandler.java
- src/main/java/site/sonisori/sonisori/config/SecurityConfig.java
- src/main/java/site/sonisori/sonisori/controller/UserController.java
- src/main/java/site/sonisori/sonisori/dto/user/AuthResponse.java
- src/main/java/site/sonisori/sonisori/service/UserService.java
- 사용자 인증 상태를 조회하는 API (`/auth`)를 구현했습니다.
- 로그인한 사용자와 비로그인 사용자의 인증 상태를 구분하여 응답하는 기능을 추가했습니다.
- AuthResponse 레코드 클래스를 사용하여 응답 데이터를 구조화했습니다.
| 사진 | 설명 |
| --- | --- |
|![image](https://github.com/user-attachments/assets/8c90062c-0d2d-4626-a89b-a5feee6c6631)| 로그인 시 |
|![image](https://github.com/user-attachments/assets/15e4fe98-6e6e-49ba-a18b-4d9a1d5550ed)| 비 로그인 시 |
closed #31
> feat: 사용자 인증 상태 조회 API 구현 

- src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
- src/main/java/site/sonisori/sonisori/controller/UserController.java
- src/main/java/site/sonisori/sonisori/service/UserService.java
- 로그아웃과 마찬가지로 리프레쉬토큰, 쿠키를 삭제하고 추가로 DB에서 삭제하는 작업까지 추가하여 회원 탈퇴 api를 구현하였습니다.
- deleteUser 의 메서드 예외처리가 잘 되었는지 확인해주세요.
| 사진 | 설명 |
| --- | --- |
|![image](https://github.com/user-attachments/assets/0931ca41-02d0-4bd2-9a1e-415b7dcbee23)| api호출 전 |
|![image](https://github.com/user-attachments/assets/c3b81373-f157-43b2-976e-386ce7733bb2) | api호출 성공 |
|![image](https://github.com/user-attachments/assets/abb16b55-6de7-431f-923c-6f1f25156f55)| api호출 후 db에서 삭제된 모습 |
- 논의할 사항이 있다면 적어주세요.
closed #41
> feat: 회원탈퇴 api 구현

- src/main/java/site/sonisori/sonisori/auth/jwt/JwtUtil.java
- src/main/java/site/sonisori/sonisori/controller/UserController.java
- refreshToken 기반으로 accessToken 을 재발급하는 api를 구현하였습니다.
- accessToken 을 재발급하는 메서드인 reissueAccessToken 에서 놓친 예외처리가 있는지 확인해주세요
- 
| 사진 | 설명 |
| --- | --- |
|![image](https://github.com/user-attachments/assets/36dc9e28-bbb2-4ca1-8b0d-666eb5daf357) | 로그인시 accessToken 값 |
|![image](https://github.com/user-attachments/assets/ede08546-4427-4154-9e3e-5bef2c089437) |재발급 api 호출 후 변경된acessToken 값 |
|![image](https://github.com/user-attachments/assets/03d3d1a9-dc06-4122-b1ae-6d9c9ebaa087) | 로그인시 refeshToken 값 |
|![image](https://github.com/user-attachments/assets/b3dd6705-d806-462d-ada5-7b4d0d07f1d3) | 재발급 api호출 후에도 동일한 refreshToken 값 |
- controller에서 addCookies 전에 deleteCookies도 호출하려 했으나 찾아본 결과 굳이 호출하지 않아도 덮어씌우기 때문에 괜찮다고 하여 addCookies만 호출했습니다.
closed #43
> feat: 토큰 재발급 api 구현

- src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
- src/main/java/site/sonisori/sonisori/controller/QuizHistoryController.java
- src/main/java/site/sonisori/sonisori/dto/quizhistory/QuizHistoryRequest.java
- src/main/java/site/sonisori/sonisori/dto/quizhistory/QuizHistoryResponse.java
- src/main/java/site/sonisori/sonisori/entity/QuizHistory.java
- src/main/java/site/sonisori/sonisori/exception/GlobalExceptionHandler.java
- src/main/java/site/sonisori/sonisori/repository/QuizHistoryRepository.java
- src/main/java/site/sonisori/sonisori/service/QuizHistoryService.java
- 퀴즈 결과 제출 api를 작성하였습니다.
- api 호출 시 퀴즈 결과가 저장됩니다. 
- 코드를 실행하시기 전에 quiz_histories 테이블에서 count가 올바르게 삭제되었는지 확인해주세요 
- 삭제되어있지 않다면 해당 api 호출 시에 문제가 생깁니다.
- 우선 한 토픽에 대하여 여러번 퀴즈를 제출했을 경우 마지막으로 제출한 퀴즈의 기록만 보이게됩니다
- 이 부분은 기획 관련된 부분으로.. 추후 퀴즈 제출 기록같은 UI를 만든다면 로직을 수정하겠습니다
- 우선, 최후의 기록만 보이는 것 같아서 아래와 같이 로직을 작성하였습니다
- 해당 topic에 대한 user의 기록이 없다면 새로 생성
- 있다면, update 
| 사진 | 설명 |
| --- | --- |
|![image](https://github.com/user-attachments/assets/a8ebe238-4bc5-4f5d-8156-196eabfa5206) | api 호출 시 |
| ![image](https://github.com/user-attachments/assets/f705fd3d-f730-44ad-91b4-d7dd914a4f86) | api 호출 후 isCompleted true로 수정됨 |
|![image](https://github.com/user-attachments/assets/24248522-617f-4238-b27e-fe89c5d1b25b)| 초과시 |
|![image](https://github.com/user-attachments/assets/1f2f91f9-266 …
> feat: 퀴즈 결과 제출 및 퀴즈 기록 저장 api 구현 

- src/main/java/site/sonisori/sonisori/auth/jwt/JwtUtil.java
- src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
- src/main/java/site/sonisori/sonisori/common/response/SuccessResponse.java
- src/main/java/site/sonisori/sonisori/config/ExceptionHandlerConfig.java
- src/main/java/site/sonisori/sonisori/config/SecurityConfig.java
- src/main/java/site/sonisori/sonisori/controller/SignTopicController.java
- src/main/java/site/sonisori/sonisori/dto/signtopic/AddSignTopicRequest.java
- src/main/java/site/sonisori/sonisori/dto/signtopic/SignTopicRequest.java
- src/main/java/site/sonisori/sonisori/service/SignTopicService.java
- 관리자 토픽 추가 api를 구현하였습니다.
- 본래 Request Body에 토픽 title과 토픽 contents 만 넘어오는 것으로 되어있었으나 difficulty도 함께 설정하는게 맞는 것 같아 difficulty도 Dto에 추가해서 구현하였습니다. (함께 설정하는게 아니라면 수정하겠습니다)
- 예외처리부분에서 놓친게 없나 확인해주세요
- Controller 에서 저번에 말씀해주신 데이터 가공 문제, 서비스계층 구현체의존성 문제 가 발생하지 않았는지 확인해주세요 (이 부분이 아직 헷갈려서 아마 놓친 부분이 있을 수도 있습니다ㅜ)
| 사진 | 설명 |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/e5b22f68-d37d-4ace-911e-98f6a6700886) | api호출시 topicId 반환 |
| ![image](https://github.com/user-attachments/assets/f75b4056-98a9-4c1e-b008-e44676b91bdb) | db에도 저장된 모습 |
- topicId가 3인 이유는 제가 앞서 테스트하느라 2개를 확인하고 나서 DELETE로 비우고 다시 저장해서 그렇습니다..
closed #45
> feat: 관리자 토픽 추가 api구현

- src/main/java/site/sonisori/sonisori/controller/SignTopicController.java
- src/main/java/site/sonisori/sonisori/service/SignTopicService.java
- 관리자 토픽 삭제 api를 구현하였습니다.
- 일반 USER권한으로 접근시 403에러, 존재하지 않는 topicId 삭제요청시 404에러, 성공시 204 로 구현하였습니다.
에러처리가 잘못된게 있는지 봐주세요!
| 사진 | 설명 |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/4aa97e94-d1c6-4463-a1cd-2d935ac9c206) | 유저 권한으로 접근시 |
| ![image](https://github.com/user-attachments/assets/11a60fa3-8efd-4171-817f-5c50d34425bb) | 존재하지 않는 topicId 삭제 요청시 |
| ![image](https://github.com/user-attachments/assets/fb0b5905-4866-485b-b3af-b18778bbf5c5)  | 삭제 요청 성공(DB에서도 잘 삭제됩니다!) |
closed #53
> feat: 관리자 토픽삭제기능 구현

- src/main/java/site/sonisori/sonisori/controller/SignQuizController.java
- src/main/java/site/sonisori/sonisori/dto/signquiz/SignQuizRequest.java
- src/main/java/site/sonisori/sonisori/entity/SignTopic.java
- src/main/java/site/sonisori/sonisori/service/SignQuizService.java
- src/main/java/site/sonisori/sonisori/service/SignTopicService.java
- src/main/java/site/sonisori/sonisori/service/UserService.java
- 관리자 퀴즈 추가 기능을 구현하였습니다.
- 퀴즈 추가시 201, USER권한 접근시 403에러, 존재하지 않는 토픽에 추가 시도시 404에러로 구현하였습니다.
- RequestBody양식은 topicId/topicName, sentence였으나 url에 입력되는 topicId를 활용하면 될 것 같아 sentence만 Request 받는 것으로 구현하였습니다.
- addQuiz 메서드로 퀴즈 추가시 SignTopic의 totalQuizzes를 +1 하도록 구현하였습니다.
- 예외처리 부분에서 놓친게 있나 확인해주세요.
| 사진 | 설명 |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/5eae8d82-9386-4eaf-977c-42afc31ae320) | 퀴즈 추가 성공 |
| ![image](https://github.com/user-attachments/assets/2ea550da-65e9-4f22-a56e-ad00bae97c51) | DB에 추가된 퀴즈 모습 |
| ![image](https://github.com/user-attachments/assets/a3fb4922-16e9-4544-9136-3df7a60a1d02) | totalQuizzes가 1이 된 모습 |
| ![image](https://github.com/user-attachments/assets/f4b1c7e0-9cff-4fbd-98b5-db6dccb14bb4) | 존재하지 않는 토픽 접근 |
| …
> feat: 관리자 퀴즈 추가 기능 구현

- src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
- src/main/java/site/sonisori/sonisori/controller/SignQuizController.java
- src/main/java/site/sonisori/sonisori/entity/SignTopic.java
- src/main/java/site/sonisori/sonisori/service/SignQuizService.java
- 관리자 권한으로 퀴즈를 삭제하는 api 기능을 구현하였습니다.
- 존재하지 않는 quizId에 접근시 404에러, USER권한 접근시 403에러, 성공시 204를 반환하도록 구현하였습니다.
- 전달받은 quizId를 이용해 signTopic을 찾고 decrementTotalQuizzes 메서드를 구현하여 totalQuizzes 가 -1이 되도록 구현하였습니다.
- 놓친 예외처리 부분이 있나 봐주세요!
| 사진 | 설명 |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/a437ced6-a54c-46f2-9286-87bc700d0d5c) | 존재하지 않는 퀴즈 접근 |
| ![image](https://github.com/user-attachments/assets/5f101ed7-d159-4832-b20c-6069a0b3cca2) | 퀴즈 삭제 성공 |
| ![image](https://github.com/user-attachments/assets/54c65cf8-59b7-49ee-a014-cfce98823355) | 삭제 후 퀴즈가 1개만 남은 모습 |
| ![image](https://github.com/user-attachments/assets/aa073671-679b-4b1f-bb88-9805fd2782cd) | 삭제 후 totalQuizzes가 1이 된 모습 |
| ![image](https://github.com/user-attachments/assets/1e87aa82-0bda-4 …
> feat: 관리자 퀴즈 삭제기능 구현

- .github/workflows/cd.yml
- 배포 실패 원인인 환경 상태 확인 로직을 개선하여, 상태가 유효하지 않으면 배포를 진행하지 않도록 수정했습니다.
closed #67
> Fix: Elastic Beanstalk 환경 상태가 Ready가 아닌 경우 배포가 실패하는 문제 수정

- src/main/java/site/sonisori/sonisori/controller/SignQuizController.java
- src/main/java/site/sonisori/sonisori/entity/SignQuiz.java
- src/main/java/site/sonisori/sonisori/service/SignQuizService.java
- 관리자 권한으로 퀴즈를 수정하는 api 기능을 구현하였습니다.
- 존재하지 않는 퀴즈 접근시 404에러, USER권한 접근시 403에러, 수정 성공시 204로 구현하였습니다.
- @transactional 을 추가하고 dirty_checking을 이용하여 updateQuiz메서드에 save를 생략하였습니다. 
| 사진 | 설명 |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/ee776c35-4c52-4e30-83ee-a61acebf2f7f) | 퀴즈 수정 성공 |
| ![image](https://github.com/user-attachments/assets/65115c27-79bb-404c-bc33-346f3c49f327) | DB에서 수정된 모습 |
| ![image](https://github.com/user-attachments/assets/03ffc77c-522d-49cc-987a-68f38e472564) | 존재하지 않는 퀴즈 접근 |
| ![image](https://github.com/user-attachments/assets/ccfc3e87-0d75-47f1-932e-db4890d622de) | USER권한으로 접근 |
closed #66
> feat: 관리자 퀴즈 수정기능 구현

- src/main/java/site/sonisori/sonisori/controller/SignWordController.java
- src/main/java/site/sonisori/sonisori/dto/signword/SignWordRequest.java
- src/main/java/site/sonisori/sonisori/service/SignWordService.java
- 수어 사전 단어 추가 api를 구현하였습니다.
- description이 null 인 단어도 있어, description은 not null 처리를 하지 않았습니다.
| 사진 | 설명 |
| --- | --- |
|![image](https://github.com/user-attachments/assets/c1c6121d-400a-4019-ae6a-27a5c2f9d65a)| 일반 유저 |
|![image](https://github.com/user-attachments/assets/dc1569de-7967-4f0e-802d-c0ff4d2a5ad1)| 추가 성공 |
- 논의할 사항이 있다면 적어주세요.
closed #75
> feat: 수어 사전 단어 추가 api 구현

- src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2SuccessHandler.java
- src/main/java/site/sonisori/sonisori/config/SecurityConfig.java
- src/main/java/site/sonisori/sonisori/controller/UserController.java
- 배포 도메인에 맞게 cors를 설정하였습니다.
- 쿠키에 배포 도메인을 추가하였습니다.
- 확인을 위해 코드 리뷰 없이 머지하겠습니다 
closed #78
> chore: 배포 도메인 cors 설정 및 쿠키 도메인 추가

- src/main/java/site/sonisori/sonisori/common/constants/ErrorMessage.java
- src/main/java/site/sonisori/sonisori/controller/SignWordController.java
- src/main/java/site/sonisori/sonisori/service/SignWordService.java
- 관리자 권한으로 단어를 삭제하는 api 기능을 구현하였습니다.
- 존재하지 않는 단어 접근시 404에러, USER권한 접근시 403에러, 삭제 성공시 204로 구현하였습니다.
| 사진 | 설명 |
| --- | --- |
|![image](https://github.com/user-attachments/assets/b4355448-020f-4c1d-8751-352ffaaccefe) | 단어 삭제 성공 |
|![image](https://github.com/user-attachments/assets/82756aaf-65ed-46f9-b08a-7c17367d99a3) | 존재 하지 않는 단어 접근|
|![image](https://github.com/user-attachments/assets/b653ac2b-4870-4177-a655-bb171434b1fe) | USER권한 접근 |
| ![image](https://github.com/user-attachments/assets/0a594ba6-137a-4ed3-80ac-328fbe1d747a) | 잘 삭제된 모습 |
- 논의할 사항이 있다면 적어주세요.
closed #80
> feat: 관리자 단어 삭제기능 구현

- src/main/java/site/sonisori/sonisori/config/SecurityConfig.java
- src/main/java/site/sonisori/sonisori/controller/SignWordController.java
- src/main/java/site/sonisori/sonisori/dto/signword/SignWordDetailResponse.java
- src/main/java/site/sonisori/sonisori/dto/signwordresource/SignWordResourceDto.java
- src/main/java/site/sonisori/sonisori/dto/signwordresource/SignWordResourceListRequest.java
- src/main/java/site/sonisori/sonisori/entity/SignWord.java
- src/main/java/site/sonisori/sonisori/service/SignWordService.java
- src/main/resources/db/migration/V5__add_cascade_settings.sql
- 단어 개별(디테일) 조회 api를 구현하였습니다.
- 단어와 설명, 이미지 url과 video url을 포함합니다. 
| 사진 | 설명 |
| --- | --- |
|![image](https://github.com/user-attachments/assets/ef8f0391-c148-40a8-ad3c-380e334abec6) | 디테일 조회 1|
|![image](https://github.com/user-attachments/assets/0b275c65-3561-48d3-a095-0f3dd8799c62)|디테일 조회 2|
|![image](https://github.com/user-attachments/assets/4532d6b2-f970-40e0-b7df-4b6af604e28f)|존재하지 않는 단어|
- 논의할 사항이 있다면 적어주세요.
closed #74
> feat: 단어 개별 조회 api 구현 (+oauth2 경로 추가, cascade 설정 추가)

- src/main/java/site/sonisori/sonisori/controller/SignWordController.java
- src/main/java/site/sonisori/sonisori/entity/SignWord.java
- src/main/java/site/sonisori/sonisori/service/SignWordService.java
- 관리자 기능으로 단어를 수정하는 api를 구현하였습니다.
- 없는 단어 접근시 404, USER권한 접근시 403, 수정 성공시 204로 구현하였습니다.
| 사진 | 설명 |
| --- | --- |
|![image](https://github.com/user-attachments/assets/c597a25c-5b0c-45d1-9b71-3ff8990b27af) | 수정 성공 |
|![image](https://github.com/user-attachments/assets/c07568e9-80c3-40ef-9dd2-defc14ca7de6) | DB에 반영된 모습 |
|![image](https://github.com/user-attachments/assets/a36cdbc1-e764-4f98-aed4-0ffbc05e70f2) | 존재하지 않는 단어 접근 |
|![image](https://github.com/user-attachments/assets/21dfd7c2-c7d9-46e4-bd83-c292210a498a) | USER권한 접근 |
closed #84
> feat: 관리자 단어 수정기능 구현
